CREATE TYPE "public"."complaint_report_status" AS ENUM('pending', 'recorded', 'unattributed');--> statement-breakpoint
CREATE TABLE "complaint_reports" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant_id" text,
	"phone_hash" text NOT NULL,
	"source" "complaint_source" NOT NULL,
	"reporter" text NOT NULL,
	"external_ref" text,
	"notes" text,
	"reported_at" timestamp with time zone DEFAULT now() NOT NULL,
	"status" "complaint_report_status" DEFAULT 'pending' NOT NULL,
	"complaint_id" text,
	"processed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "complaint_reports_id_format" CHECK ("id" ~ '^crp_[0-9A-HJKMNP-TV-Z]{26}$'),
	CONSTRAINT "complaint_reports_notes_len" CHECK ("complaint_reports"."notes" is null or char_length("complaint_reports"."notes") <= 1000)
);
--> statement-breakpoint
ALTER TABLE "complaint_reports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "call_attempts" ADD COLUMN "media_purged_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "complaint_reports" ADD CONSTRAINT "complaint_reports_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complaint_reports" ADD CONSTRAINT "complaint_reports_complaint_id_complaints_id_fk" FOREIGN KEY ("complaint_id") REFERENCES "public"."complaints"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "complaint_reports_pending_idx" ON "complaint_reports" USING btree ("reported_at") WHERE "complaint_reports"."status" = 'pending';--> statement-breakpoint
CREATE INDEX "complaint_reports_tenant_idx" ON "complaint_reports" USING btree ("tenant_id","reported_at");--> statement-breakpoint
CREATE INDEX "call_attempts_media_retention_idx" ON "call_attempts" USING btree ("tenant_id","ended_at") WHERE "call_attempts"."media_purged_at" is null and ("call_attempts"."recording_uri" is not null or "call_attempts"."transcript_uri" is not null);--> statement-breakpoint

-- 0007 (hand-written part) — compliance intake (P2-CMP-1/2/4).
ALTER TABLE complaint_reports FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
-- A tenant sees and files its own reports; null-tenant rows (public page, unattributed) are
-- visible only to the service role, which processes the queue.
CREATE POLICY tenant_isolation ON complaint_reports
  USING (tenant_id = app_tenant_id()) WITH CHECK (tenant_id = app_tenant_id());
--> statement-breakpoint
GRANT SELECT, INSERT ON complaint_reports TO naaradh_app;
GRANT SELECT, INSERT, UPDATE ON complaint_reports TO naaradh_service;
REVOKE DELETE, TRUNCATE ON complaint_reports FROM naaradh_app, naaradh_service;
--> statement-breakpoint
CREATE TRIGGER complaint_reports_set_updated_at BEFORE UPDATE ON complaint_reports
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
--> statement-breakpoint

-- Public /do-not-call page (universal rule 8, P2-CMP-2). The request path has no tenant and no
-- API key, so instead of handing it the service role it gets exactly this: a GLOBAL, indefinite
-- `self_service` suppression for one phone hash (idempotent), an audit row, and — when the person
-- also reports an unwanted call — a pending complaint report for the complaints worker to
-- attribute. Ids are generated by the caller (prefixed ULIDs); the function never reveals whether
-- the number was ever called.
CREATE OR REPLACE FUNCTION submit_dnc_request(
  p_suppression_id text,
  p_audit_id text,
  p_report_id text,
  p_phone_hash text,
  p_report boolean,
  p_ip_hash text
) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF p_phone_hash !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'invalid phone hash' USING ERRCODE = '22023';
  END IF;
  INSERT INTO suppressions (id, tenant_id, phone_hash, purpose, reason, until, created_by, notes)
  SELECT p_suppression_id, NULL, p_phone_hash, 'all', 'self_service', NULL, 'dnc_page', 'public do-not-call request'
  WHERE NOT EXISTS (
    SELECT 1 FROM suppressions s
    WHERE s.tenant_id IS NULL AND s.phone_hash = p_phone_hash AND s.purpose = 'all'
      AND s.reason = 'self_service' AND s.lifted_at IS NULL
  );
  INSERT INTO audit_log (id, tenant_id, actor_type, actor_id, action, target_type, target_id, after, ip_hash)
  VALUES (p_audit_id, NULL, 'system', 'dnc_page', 'dnc.requested', 'phone_hash', p_phone_hash,
          jsonb_build_object('report_unwanted_call', p_report), p_ip_hash);
  IF p_report THEN
    INSERT INTO complaint_reports (id, tenant_id, phone_hash, source, reporter, status)
    VALUES (p_report_id, NULL, p_phone_hash, 'self_service', 'dnc_page', 'pending');
  END IF;
END;
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION submit_dnc_request(text, text, text, text, boolean, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION submit_dnc_request(text, text, text, text, boolean, text) TO naaradh_app;
